// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\component_context\C_1_4_2\component_context_flag.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ComponentContextFlag_C_1_4_2(ctx *model.Context, c *model.Component, b *bytes.Buffer) string {
	b.WriteString(`public partial class `)
	b.WriteString(ctx.GetID().WithContextSuffix().ToUpperFirst().String())
	b.WriteString(` {

    public `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity `)
	b.WriteString(c.GetID().ToLowerFirst().String())
	b.WriteString(`Entity { get { return GetGroup(`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Matcher.`)
	b.WriteString(c.GetID().ToUpperFirst().String())
	b.WriteString(`).GetSingleEntity(); } }

    public bool `)
	b.WriteString(c.GetPrefixOrDefault().ToLowerFirst().String())
	b.WriteString(c.GetID().ToUpperFirst().String())
	b.WriteString(` {
        get { return `)
	b.WriteString(c.GetID().ToLowerFirst().String())
	b.WriteString(`Entity != null; }
        set {
            var entity = `)
	b.WriteString(c.GetID().ToLowerFirst().String())
	b.WriteString(`Entity;
            if (value != (entity != null)) {
                if (value) {
                    CreateEntity().`)
	b.WriteString(c.GetPrefixOrDefault().ToLowerFirst().String())
	b.WriteString(c.GetID().ToUpperFirst().String())
	b.WriteString(` = true;
                } else {
                    entity.Destroy();
                }
            }
        }
    }
}
`)
	return b.String()

}
