// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity\C_1_4_2\entity.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func Entity_C_1_4_2(c *model.C, b *bytes.Buffer) string {
	b.WriteString(`
public sealed partial class `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity : Entitas.Entity
{
}
`)
	return b.String()

}
