// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\event_listener_interface\C_1_6_1\event_listener_argument_pass.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func EventListenerArgumentPass_1_6_1(cp *entitas.CP, b *bytes.Buffer) string {
	ml := cp.MemberList()
	if len(ml) > 0 && cp.EventType() == entitas.AddedEvent {
		b.WriteString(", ")
		for i, m := range ml {
			b.WriteString(m.Value().String())
			b.WriteRune(' ')
			b.WriteString(m.ID().ToLowerFirst().String())
			if i != len(ml)-1 {
				b.WriteString(", ")
			}
		}
	}

	return b.String()

}
