// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\event_listener_interface\C_1_6_1\event_listener_interface.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EventListenerInterface_C_1_6_1(ctx *model.Context, c *model.Component, b *bytes.Buffer) string {
	b.WriteString(`public interface I`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String() + c.GetID().WithoutComponentSuffix().ToUpperFirst().String() + c.GetEventTypeSuffix().String())
	b.WriteString(`Listener {
    void On`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String() + c.GetEventTypeSuffix().String())
	b.WriteString(`(`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity entity`)
	EventListenerArgumentPass_1_6_1(c, b)
	b.WriteString(`);
}
`)
	return b.String()

}
