// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\event_listener_interface\C_1_6_1\event_listener_interface.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EventListenerInterface_C_1_6_1(c *model.C, cp *model.CP, b *bytes.Buffer) string {
	b.WriteString(`
public interface I`)
	b.WriteString(ComponentID(c, cp).ToUpperFirst().String())
	b.WriteString(` 
{
    void On`)
	b.WriteString(MethodID(cp).ToUpperFirst().String())
	b.WriteString(`(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity entity`)
	EventListenerArgumentPass_1_6_1(cp, b)
	b.WriteString(`);
}
`)
	return b.String()

}
