// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\event_system\C_1_6_1\event_system_any_target.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EventSystemAnyTarget_C_1_6_1(c *model.C, cp *model.CP, b *bytes.Buffer) string {
	b.WriteString(`
public sealed class `)
	b.WriteString(ComponentID(c, cp).ToUpperFirst().String())
	b.WriteString(`EventSystem : Entitas.ReactiveSystem<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> 
{   
    readonly Entitas.IGroup<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> _listeners;
    readonly System.Collections.Generic.List<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> _entityBuffer;
    readonly System.Collections.Generic.List<I`)
	b.WriteString(ComponentID(c, cp).ToUpperFirst().String())
	b.WriteString(`> _listenerBuffer;
    
    public `)
	b.WriteString(ComponentID(c, cp).ToUpperFirst().String())
	b.WriteString(`EventSystem(Contexts contexts) : base(contexts.`)
	b.WriteString(c.ID().WithoutContextSuffix().ToLowerFirst().String())
	b.WriteString(`)
    {
        _listeners = contexts.`)
	b.WriteString(c.ID().WithoutContextSuffix().ToLowerFirst().String())
	b.WriteString(`.GetGroup(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Matcher.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`);
        _entityBuffer = new System.Collections.Generic.List<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>();
        _listenerBuffer = new System.Collections.Generic.List<I`)
	b.WriteString(ComponentID(c, cp).ToUpperFirst().String())
	b.WriteString(`>();
    }
    
    protected override Entitas.ICollector<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> GetTrigger(Entitas.IContext<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> context)
    {
        return Entitas.CollectorContextExtension.CreateCollector(
            context, Entitas.TriggerOnEventMatcherExtension.`)
	b.WriteString(cp.EventType().String().String())
	b.WriteString(`(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Matcher.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`)
        );
    }
    
    protected override bool Filter(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity entity)
    {
        return`)
	b.WriteString(Filter(c, cp))
	b.WriteString(`;
    }
    
    protected override void Execute(System.Collections.Generic.List<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> entities)
    {
        foreach (var e in entities)
        {
            `)

	if len(cp.MemberList()) > 0 {
		b.WriteString("var component = e.")
		b.WriteString(cp.ID().WithoutComponentSuffix().ToLowerFirst().String())
		b.WriteRune(';')
		b.WriteRune('\n')
	}

	b.WriteString(`
            foreach (var listenerEntity in _listeners.GetEntities(_entityBuffer))
            {
                _listenerBuffer.Clear();
                _listenerBuffer.AddRange(e.`)
	b.WriteString(ComponentID(c, cp).ToLowerFirst().String())
	b.WriteString(`.value);
                foreach (var listener in _listenerBuffer)
                {
                    listener.On`)
	b.WriteString(MethodID(cp).ToUpperFirst().String())
	b.WriteString(`(e`)
	EventSystemArgumentPass_1_6_1(cp, b)
	b.WriteString(`);
                }
            }
        }
    }
}
`)
	return b.String()

}
