dist: xenial

language: go

env:
  - GO111MODULE=on

go:
  - 1.12.x

git:
  depth: 1

install: 
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

notifications:
  email: false

script:
  - go test -v -race ./... 
  - go test -v -covermode=count -coverprofile=coverage.out 
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN