// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\context_attribute\C_1_4_2\context_attribute.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ContextAttribute_C_1_4_2(ctx *model.Context, b *bytes.Buffer) string {
	b.WriteString(`public sealed class `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Attribute : Entitas.CodeGeneration.Attributes.ContextAttribute {
    
    public `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Attribute() : base("`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`") {
    }
}
`)
	return b.String()

}
