// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\component\C_1_7_0\component.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func Component_C_1_7_0(cp *entitas.CP, b *bytes.Buffer) string {
	b.WriteString(ComponentAttribute_C_1_7_0(cp))
	b.WriteString(`
public sealed partial class `)
	b.WriteString(cp.ID().WithComponentSuffix().String())
	b.WriteString(` : Entitas.IComponent 
{
`)
	for _, m := range cp.MemberList() {
		b.WriteRune('\t')
		b.WriteString(MemberAttribute_C_1_7_0(m))
		b.WriteString(`public `)
		b.WriteString(m.Value().String())
		b.WriteRune(' ')
		b.WriteString(m.ID().String())
		b.WriteString(`;`)
		b.WriteRune('\n')
	}
	b.WriteString(`
}
`)
	return b.String()

}
