// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\context_observer\C_1_4_2\context_observer.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func ContextObserver_C_1_4_2(c []*entitas.C, b *bytes.Buffer) string {
	b.WriteString(`
public partial class Contexts 
{

#if (!ENTITAS_DISABLE_VISUAL_DEBUGGING && UNITY_EDITOR)

    [Entitas.CodeGeneration.Attributes.PostConstructor]
    public void InitializeContexObservers() 
    {
        try 
        {
`)
	for _, cc := range c {
		b.WriteString("\t\t\t")
		b.WriteString(`CreateContextObserver(`)
		b.WriteString(cc.ID().WithoutContextSuffix().ToLowerFirst().String())
		b.WriteString(`);`)
		b.WriteRune('\n')
	}
	b.WriteString(`
        } 
        catch(System.Exception) 
        {
        }
    }
    public void CreateContextObserver(Entitas.IContext context) 
    {
        if (UnityEngine.Application.isPlaying) 
        {
            var observer = new Entitas.VisualDebugging.Unity.ContextObserver(context);
            UnityEngine.Object.DontDestroyOnLoad(observer.gameObject);
        }
    }

#endif

}
`)
	return b.String()

}
