// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\entity_index\C_1_4_2\custom_constants.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	proton "github.com/SirMetathyst/go-proton"
)

func EntityIndexCustomConstants_C_1_4_2(ei []*proton.EntityIndex, b *bytes.Buffer) string {
	for _, cei := range ei {
		ID := cei.ID().String()
		b.WriteRune('\t')
		b.WriteString(`public const string`)
		b.WriteRune(' ')
		b.WriteString(ID)
		b.WriteString(` = "`)
		b.WriteString(ID)
		b.WriteString(`";`)
		b.WriteString("\n")
	}
	return b.String()

}
