// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\entity_index\C_1_4_2\get_custom_indices.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func EntityIndexGetCustomIndices_C_1_4_2(ei []*entitas.EI, b *bytes.Buffer) string {
	for _, cei := range ei {
		IndexType := cei.ID().String()
		ReturnType := ""
		if !cei.IsPrimary() {
			ReturnType = "System.Collections.Generic.HashSet<" + cei.Context().ID().WithoutContextSuffix().ToUpperFirst().String() + "Entity>"
		} else {
			ReturnType = cei.Context().ID().WithoutContextSuffix().ToUpperFirst().String() + "Entity"
		}
		for _, eim := range cei.EntityIndexMethodList() {
			b.WriteString(`
    public static `)
			b.WriteString(ReturnType)
			b.WriteRune(' ')
			b.WriteString(eim.ID().String())
			b.WriteString(`(this `)
			b.WriteString(cei.Context().ID().WithContextSuffix().ToUpperFirst().String())
			b.WriteString(` context, `)
			EntityIndexArgument_C_1_4_2(eim, b)
			b.WriteString(`) => ((`)
			b.WriteString(IndexType)
			b.WriteString(`)(context.GetEntityIndex(Contexts.`)
			b.WriteString(IndexType)
			b.WriteString(`))).`)
			b.WriteString(eim.ID().String())
			b.WriteString(`(`)
			EntityIndexArgumentPass_C_1_4_2(eim, b)
			b.WriteString(`);`)
		}
	}
	return b.String()

}
