// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\component\E_1_4_2\event_component.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/go-proton"
)

func EventComponent_E_1_4_2(cp *proton.CP, b *bytes.Buffer) string {
	b.WriteString(`
public sealed partial class `)
	b.WriteString(eventComponentID(cp).WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`Component : Entitas.IComponent 
{
    public System.Collections.Generic.List<I`)
	b.WriteString(eventComponentID(cp).WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`> value;
}
`)
	return b.String()

}
