// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\context_observer\C_1_4_2\context_observer.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ContextObserver_C_1_4_2(ctx []*model.Context, b *bytes.Buffer) string {
	b.WriteString(`public partial class Contexts {
#if (!ENTITAS_DISABLE_VISUAL_DEBUGGING && UNITY_EDITOR)
    [Entitas.CodeGeneration.Attributes.PostConstructor]
    public void InitializeContexObservers() {
        try {
`)
	for _, cctx := range ctx {
		b.WriteString("\t\t\t")
		b.WriteString(`CreateContextObserver(`)
		b.WriteString(cctx.GetID().WithoutContextSuffix().ToLowerFirst().String())
		b.WriteString(`);`)
		b.WriteRune('\n')
	}
	b.WriteString(`
        } catch(System.Exception) {
        }
    }
    public void CreateContextObserver(Entitas.IContext context) {
        if (UnityEngine.Application.isPlaying) {
            var observer = new Entitas.VisualDebugging.Unity.ContextObserver(context);
            UnityEngine.Object.DontDestroyOnLoad(observer.gameObject);
        }
    }
#endif
}
`)
	return b.String()

}
