// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\add_custom_indices.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexAddCustomIndices_C_1_4_2(ei []*model.EntityIndex, b *bytes.Buffer) string {
	for _, e := range ei {
		if e.GetContext() != nil {
			b.WriteString("\t\t")
			b.WriteString(e.GetContext().GetID().WithoutContextSuffix().ToLowerFirst().String())
			b.WriteString(`.AddEntityIndex(new `)
			b.WriteString(e.GetID().String())
			b.WriteString(`(`)
			b.WriteString(e.GetContext().GetID().WithoutContextSuffix().ToLowerFirst().String())
			b.WriteString(`));`)
			b.WriteRune('\n')
		}
	}
	return b.String()

}
