// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\entity_index\C_1_4_2\add_custom_indices.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func EntityIndexAddCustomIndices_C_1_4_2(ei []*entitas.EI, b *bytes.Buffer) string {

	for _, cei := range ei {
		if cei.Context() != nil {
			b.WriteString("\t\t")
			b.WriteString(cei.Context().ID().WithoutContextSuffix().ToLowerFirst().String())
			b.WriteRune('.')
			b.WriteString("AddEntityIndex(new ")
			b.WriteString(cei.ID().String())
			b.WriteRune('(')
			b.WriteString(cei.Context().ID().WithoutContextSuffix().ToLowerFirst().String())
			b.WriteString("));\n")
		}
	}
	return b.String()

}
