// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\add_indices.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexAddIndices_C_1_4_2(c []*model.Component, b *bytes.Buffer) string {
	for _, cc := range c {
		for _, cctx := range cc.GetContext() {
			for _, m := range cc.GetMember() {
				if m.GetEntityIndex() > 0 {

					ID := cc.GetID().WithoutComponentSuffix().ToUpperFirst().String()
					Type := m.GetValue().String()
					IndexType := ""
					if m.GetEntityIndex() == 1 {
						IndexType = "Entitas.PrimaryEntityIndex"
					} else if m.GetEntityIndex() > 1 {
						IndexType = "Entitas.EntityIndex"
					}

					b.WriteString("\t\t")
					b.WriteString(cctx.GetID().WithoutContextSuffix().ToLowerFirst().String())
					b.WriteString(`.AddEntityIndex(new `)
					b.WriteString(IndexType)
					b.WriteString(`<`)
					b.WriteString(cctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
					b.WriteString(`Entity, `)
					b.WriteString(Type)
					b.WriteString(`>(
`)
					if cc.GetEntityIndexCount() == 1 {
						b.WriteString("\t\t\t")
						b.WriteString(ID)
					} else if cc.GetEntityIndexCount() > 1 {
						b.WriteString("\t\t\t")
						b.WriteString(ID)
						b.WriteString(m.GetID().ToUpperFirst().String())

					}
					b.WriteString(`,`)
					b.WriteString(cctx.GetID().WithoutContextSuffix().ToLowerFirst().String())
					b.WriteString(`.GetGroup(`)
					b.WriteString(cctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
					b.WriteString(`Matcher.`)
					b.WriteString(ID)
					b.WriteString(`), (e, c) => ((`)
					b.WriteString(cc.GetID().WithComponentSuffix().ToUpperFirst().String())
					b.WriteString(`)c).`)
					b.WriteString(m.GetID().ToLowerFirst().String())
					b.WriteString(`));`)
					b.WriteString("\n")
				}
			}
		}
	}
	return b.String()

}
