// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\argument.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexArgument_C_1_4_2(eim *model.EntityIndexMethod, b *bytes.Buffer) string {
	ms := eim.GetMember()
	for i, m := range ms {
		b.WriteString(m.GetValue().String())
		b.WriteRune(' ')
		b.WriteString(m.GetID().ToLowerFirst().String())
		if i != len(ms)-1 {
			b.WriteString(", ")
		}
	}

	return b.String()

}
