// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\entity_index\C_1_4_2\argument_pass.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func EntityIndexArgumentPass_C_1_4_2(eim *entitas.EIM, b *bytes.Buffer) string {
	ml := eim.MemberList()
	for i, m := range ml {
		b.WriteString(m.ID().ToLowerFirst().String())
		if i != len(ml)-1 {
			b.WriteString(", ")
		}
	}

	return b.String()

}
