// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\constants.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexConstants_C_1_4_2(c []*model.Component, b *bytes.Buffer) string {
	for _, cc := range c {
		ID := cc.GetID().WithoutComponentSuffix().ToUpperFirst().String()
		if cc.GetEntityIndexCount() == 1 {

			b.WriteRune('\t')
			b.WriteString(`public const string`)
			b.WriteRune(' ')
			b.WriteString(ID)
			b.WriteString(` = "`)
			b.WriteString(ID)
			b.WriteString(`";`)
			b.WriteString("\n")
		} else if cc.GetEntityIndexCount() > 1 {
			for _, m := range cc.GetMember() {

				b.WriteRune('\t')
				b.WriteString(`public const string`)
				b.WriteRune(' ')
				b.WriteString(ID)
				b.WriteString(m.GetID().ToUpperFirst().String())
				b.WriteString(` = "`)
				b.WriteString(ID)
				b.WriteString(m.GetID().ToUpperFirst().String())
				b.WriteString(`";`)
				b.WriteString("\n")

			}
		}
	}
	return b.String()

}
