// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\custom_constants.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexCustomConstants_C_1_4_2(ei []*model.EntityIndex, b *bytes.Buffer) string {
	for _, e := range ei {
		ID := e.GetID().String()
		b.WriteRune('\t')
		b.WriteString(`public const string`)
		b.WriteRune(' ')
		b.WriteString(ID)
		b.WriteString(` = "`)
		b.WriteString(ID)
		b.WriteString(`";`)
		b.WriteString("\n")
	}
	return b.String()

}
