// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\get_custom_indices.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexGetCustomIndices_C_1_4_2(ei []*model.EntityIndex, b *bytes.Buffer) string {
	for _, e := range ei {
		if e.GetContext() != nil {
			IndexType := e.GetID().String()

			ReturnType := ""
			if !e.IsPrimary() {
				ReturnType = "System.Collections.Generic.HashSet<" + e.GetContext().GetID().WithoutContextSuffix().ToUpperFirst().String() + "Entity>"
			} else {
				ReturnType = e.GetContext().GetID().WithoutContextSuffix().ToUpperFirst().String() + "Entity"
			}

			for _, eim := range e.GetEntityIndexMethod() {

				b.WriteString(`
public static `)
				b.WriteString(ReturnType)
				b.WriteRune(' ')
				b.WriteString(eim.GetID().String())
				b.WriteString(`(this `)
				b.WriteString(e.GetContext().GetID().WithContextSuffix().ToUpperFirst().String())
				b.WriteString(` context, `)
				EntityIndexArgument_C_1_4_2(eim, b)
				b.WriteString(`) {
        return ((`)
				b.WriteString(IndexType)
				b.WriteString(`)(context.GetEntityIndex(Contexts.`)
				b.WriteString(IndexType)
				b.WriteString(`))).`)
				b.WriteString(eim.GetID().String())
				b.WriteString(`(`)
				EntityIndexArgumentPass_C_1_4_2(eim, b)
				b.WriteString(`);
}

`)
			}
		}
	}
	return b.String()

}
