// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\get_custom_indices.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexGetCustomIndices_C_1_4_2(ei []*model.EI, b *bytes.Buffer) string {
	for _, cei := range ei {

		IndexType := cei.ID().String()

		ReturnType := ""
		if !cei.IsPrimary() {
			ReturnType = "System.Collections.Generic.HashSet<" + cei.Context().ID().WithoutContextSuffix().ToUpperFirst().String() + "Entity>"
		} else {
			ReturnType = cei.Context().ID().WithoutContextSuffix().ToUpperFirst().String() + "Entity"
		}

		for _, eim := range cei.EntityIndexMethodList() {

			b.WriteString(`
public static `)
			b.WriteString(ReturnType)
			b.WriteRune(' ')
			b.WriteString(eim.ID().String())
			b.WriteString(`(this `)
			b.WriteString(cei.Context().ID().WithContextSuffix().ToUpperFirst().String())
			b.WriteString(` context, `)
			EntityIndexArgument_C_1_4_2(eim, b)
			b.WriteString(`) 
{
    return ((`)
			b.WriteString(IndexType)
			b.WriteString(`)(context.GetEntityIndex(Contexts.`)
			b.WriteString(IndexType)
			b.WriteString(`))).`)
			b.WriteString(eim.ID().String())
			b.WriteString(`(`)
			EntityIndexArgumentPass_C_1_4_2(eim, b)
			b.WriteString(`);
}

`)
		}
	}
	return b.String()

}
