// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\entity_index\C_1_4_2\get_indices.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EntityIndexGetIndices_C_1_4_2(c []*model.Component, b *bytes.Buffer) string {
	for _, cc := range c {
		for _, cctx := range cc.GetContext() {
			for _, m := range cc.GetMember() {
				if m.GetEntityIndex() > 0 {

					ID := cc.GetID().WithoutComponentSuffix().ToUpperFirst().String()
					Type := m.GetValue().String()
					MemberName := m.GetID().ToLowerFirst().String()
					IndexName := ""
					IndexType := ""
					if m.GetEntityIndex() == 1 {
						IndexType = "Entitas.PrimaryEntityIndex"
					} else if m.GetEntityIndex() > 1 {
						IndexType = "Entitas.EntityIndex"
					}

					if cc.GetEntityIndexCount() == 1 {
						IndexName = ID
					} else if cc.GetEntityIndexCount() > 1 {
						IndexName = ID + m.GetID().ToUpperFirst().String()
					}
					if m.GetEntityIndex() == 1 {
						b.WriteRune('\t')
						b.WriteString(`public static `)
						b.WriteString(cctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
						b.WriteString(`Entity GetEntityWith`)
						b.WriteString(IndexName)
						b.WriteString(`(this `)
						b.WriteString(cctx.GetID().WithContextSuffix().ToUpperFirst().String())
						b.WriteString(` context, `)
						b.WriteString(Type)
						b.WriteRune(' ')
						b.WriteString(MemberName)
						b.WriteString(`) {
        return ((`)
						b.WriteString(IndexType)
						b.WriteString(`<`)
						b.WriteString(cctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
						b.WriteString(`Entity, `)
						b.WriteString(Type)
						b.WriteString(`>)context.GetEntityIndex(Contexts.`)
						b.WriteString(IndexName)
						b.WriteString(`)).GetEntity(`)
						b.WriteString(MemberName)
						b.WriteString(`); 
    }`)
						b.WriteRune('\n')

					} else if m.GetEntityIndex() > 1 {
						b.WriteRune('\t')
						b.WriteString(`public static System.Collections.Generic.HashSet<`)
						b.WriteString(cctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
						b.WriteString(`Entity> GetEntitiesWith`)
						b.WriteString(IndexName)
						b.WriteString(`(this `)
						b.WriteString(cctx.GetID().WithContextSuffix().ToUpperFirst().String())
						b.WriteString(` context, `)
						b.WriteString(Type)
						b.WriteRune(' ')
						b.WriteString(MemberName)
						b.WriteString(`) {
        return ((`)
						b.WriteString(IndexType)
						b.WriteString(`<`)
						b.WriteString(cctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
						b.WriteString(`Entity, `)
						b.WriteString(Type)
						b.WriteString(`>)context.GetEntityIndex(Contexts.`)
						b.WriteString(IndexName)
						b.WriteString(`)).GetEntities(`)
						b.WriteString(MemberName)
						b.WriteString(`); 
    }`)
					}
				}
			}
		}
	}
	return b.String()

}
