// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\context\C_1_4_2\context.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func Context_C_1_4_2(c *model.C, b *bytes.Buffer) string {
	b.WriteString(`
public sealed partial class `)
	b.WriteString(c.ID().WithContextSuffix().ToUpperFirst().String())
	b.WriteString(` : Entitas.Context<`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> 
{
    public `)
	b.WriteString(c.ID().WithContextSuffix().ToUpperFirst().String())
	b.WriteString(`()
        : base(
            `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.TotalComponents,
            0,
            new Entitas.ContextInfo(
                "`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`",
                `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.componentNames,
                `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.componentTypes
            ),
            (entity) =>
#if (ENTITAS_FAST_AND_UNSAFE)
            new Entitas.UnsafeAERC()
#else
            new Entitas.SafeAERC(entity)
#endif
        ) 
    {
    }
}
`)
	return b.String()

}
