// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\contexts\C_1_4_2\contexts.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func Contexts_C_1_4_2(ctx []*model.Context, b *bytes.Buffer) string {
	b.WriteString(`public partial class Contexts : Entitas.IContexts {

    public static Contexts sharedInstance {
        get {
			if (_sharedInstance == null) {
				_sharedInstance = new Contexts();
            }
            return _sharedInstance;
        }
        set { _sharedInstance = value; }
    }
  
    static Contexts _sharedInstance;

`)
	for _, cctx := range ctx {
		b.WriteRune('\t')
		b.WriteString(`public `)
		b.WriteString(cctx.GetID().WithContextSuffix().ToUpperFirst().String())
		b.WriteRune(' ')
		b.WriteString(cctx.GetID().WithoutContextSuffix().ToLowerFirst().String())
		b.WriteString(` { get; set; }`)
		b.WriteRune('\n')
	}
	b.WriteString(`

    public Entitas.IContext[] allContexts { get { return new Entitas.IContext [] { `)
	for Index, cctx := range ctx {
		b.WriteString(cctx.GetID().WithoutContextSuffix().ToLowerFirst().String())
		if Index != len(ctx)-1 {
			b.WriteString(", ")
		}
	}
	b.WriteString(` }; } }
  
	public Contexts() {

`)
	for _, cctx := range ctx {
		b.WriteString("\t\t")
		b.WriteString(cctx.GetID().WithoutContextSuffix().ToLowerFirst().String())
		b.WriteString(` = new `)
		b.WriteString(cctx.GetID().WithContextSuffix().ToUpperFirst().String())
		b.WriteString(`();`)
		b.WriteRune('\n')
	}
	b.WriteString(`

        var postConstructors = System.Linq.Enumerable.Where(
            GetType().GetMethods(),
            method => System.Attribute.IsDefined(method, typeof(Entitas.CodeGeneration.Attributes.PostConstructorAttribute))
        );
  
        foreach (var postConstructor in postConstructors) {
            postConstructor.Invoke(this, null);
        }
    }
  
    public void Reset() {
        var contexts = allContexts;
        for (int i = 0; i < contexts.Length; i++) {
            contexts[i].Reset();
        }
    }
}
`)
	return b.String()

}
