// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\contexts\C_1_4_2\contexts.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func Contexts_C_1_4_2(c []*entitas.C, b *bytes.Buffer) string {
	b.WriteString(`
public partial class Contexts : Entitas.IContexts 
{
    public static Contexts sharedInstance 
    {
        get 
        {
			if (_sharedInstance == null)
            {
				_sharedInstance = new Contexts();
            }
            return _sharedInstance;
        }
        set 
        {
            _sharedInstance = value; 
        }
    }
  
    static Contexts _sharedInstance;

`)
	for _, cc := range c {
		b.WriteRune('\t')
		b.WriteString(`public `)
		b.WriteString(cc.ID().WithContextSuffix().ToUpperFirst().String())
		b.WriteRune(' ')
		b.WriteString(cc.ID().WithoutContextSuffix().ToLowerFirst().String())
		b.WriteString(` { get; set; }`)
		b.WriteRune('\n')
	}
	b.WriteString(`

    public Entitas.IContext[] allContexts 
    {
        get 
        { 
            return new Entitas.IContext [] { `)
	for Index, cc := range c {
		b.WriteString(cc.ID().WithoutContextSuffix().ToLowerFirst().String())
		if Index != len(c)-1 {
			b.WriteString(", ")
		}
	}
	b.WriteString(` };
        } 
    }
  
	public Contexts()
    {
`)
	for _, cc := range c {
		b.WriteString("\t\t")
		b.WriteString(cc.ID().WithoutContextSuffix().ToLowerFirst().String())
		b.WriteString(` = new `)
		b.WriteString(cc.ID().WithContextSuffix().ToUpperFirst().String())
		b.WriteString(`();`)
		b.WriteRune('\n')
	}
	b.WriteString(`

        var postConstructors = System.Linq.Enumerable.Where(
            GetType().GetMethods(),
            method => System.Attribute.IsDefined(method, typeof(Entitas.CodeGeneration.Attributes.PostConstructorAttribute))
        );
  
        foreach (var postConstructor in postConstructors)
        {
            postConstructor.Invoke(this, null);
        }
    }
  
    public void Reset() 
    {
        var contexts = allContexts;
        for (int i = 0; i < contexts.Length; i++)
        {
            contexts[i].Reset();
        }
    }
}
`)
	return b.String()

}
