// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\component_entity_interface\C_1_4_2\argument.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func ComponentEntityInterfaceArgument_C_1_4_2(cp *entitas.CP, b *bytes.Buffer) string {
	ms := cp.MemberSlice()
	for i, m := range ms {
		b.WriteString(m.Value().String())
		b.WriteRune(' ')
		b.WriteString("new")
		b.WriteString(m.ID().ToUpperFirst().String())
		if i != len(ms)-1 {
			b.WriteString(", ")
		}
	}
	return b.String()

}
