// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\component_entity_interface\C_1_4_2\component_entity_interface_flag.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ComponentEntityInterfaceFlag_C_1_4_2(cp *model.CP, b *bytes.Buffer) string {
	b.WriteString(`
public interface I`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`Entity 
{
    bool `)
	b.WriteString(cp.FlagPrefixOrDefault().ToLowerFirst().String())
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(` 
    { 
        get; 
        set; 
    }
}
`)
	return b.String()

}
