// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\component_entity_interface\C_1_4_2\component_entity_interface_argument.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ComponentEntityInterfaceArgument_C_1_4_2(c *model.Component, b *bytes.Buffer) string {
	ms := c.GetMember()
	for i, m := range ms {
		b.WriteString(m.GetValue().String())
		b.WriteRune(' ')
		b.WriteString("new")
		b.WriteString(m.GetID().ToUpperFirst().String())
		if i != len(ms)-1 {
			b.WriteString(", ")
		}
	}
	return b.String()

}
