// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\event_systems\C_1_6_1\event_systems.hero
// DO NOT EDIT!
package generator

import (
	"bytes"
	"sort"
	"strconv"

	proton "github.com/SirMetathyst/go-proton"
)

func EventSystems_C_1_6_1(c *proton.C, cp []*proton.CP, b *bytes.Buffer) string {
	b.WriteString(`
public sealed partial class `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`EventSystems : Feature
{
    public `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`EventSystems(Contexts contexts) 
    {
`)

	sort.Sort(byPriority(cp))
	cpc := 0
	for _, ccp := range cp {
		b.WriteString("\t\tAdd(new ")
		b.WriteString(componentID(c, ccp).ToUpperFirst().String())
		b.WriteString("EventSystem(contexts));")
		b.WriteString(" // priority: ")
		b.WriteString(strconv.Itoa(ccp.EventPriority()))
		if cpc != len(cp)-1 {
			b.WriteRune('\n')
		}
		cpc++
	}

	b.WriteString(`
    }
}
`)
	return b.String()

}
