// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\event_listener_component\C_1_6_1\event_listener_component.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func EventListenerComponent_C_1_6_1(ctx *model.Context, c *model.Component, b *bytes.Buffer) string {
	b.WriteString(`
[Entitas.CodeGeneration.Attributes.DontGenerate(false)]
public sealed class `)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`ListenerComponent : Entitas.IComponent {
    public System.Collections.Generic.List<I`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String() + c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`Listener> value;
}
`)
	return b.String()

}
