// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\context_matcher\E_1_4_2\context_matcher.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ContextMatcher_E_1_4_2(ctx *model.Context, b *bytes.Buffer) string {
	b.WriteString(`public sealed partial class `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Matcher {

    public static Entitas.IAllOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AllOf(params int[] Index) => Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AllOf(Index);
    public static Entitas.IAllOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AllOf(params Entitas.IMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>[] Matcher) => Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AllOf(Matcher);
    public static Entitas.IAnyOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AnyOf(params int[] Index) => Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AnyOf(Index);
    public static Entitas.IAnyOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AnyOf(params Entitas.IMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>[] Matcher) => Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AnyOf(Matcher);

}
`)
	return b.String()

}
