// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\component\C_1_4_2\component.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func Component_C_1_4_2(c *model.Component, b *bytes.Buffer) string {
	b.WriteString(`public sealed class `)
	b.WriteString(c.GetID().ToUpperFirst().WithComponentSuffix().String())
	b.WriteString(` : Entitas.IComponent {
`)
	for _, m := range c.GetMember() {
		b.WriteString(`    public `)
		b.WriteString(m.GetValue().String())
		b.WriteRune(' ')
		b.WriteString(m.GetID().ToLowerFirst().String())
		b.WriteString(`;
`)
	}
	b.WriteString(`}`)
	return b.String()

}
