// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-proton\generator\component\E_1_4_2\event_component.hero
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func EventComponent_E_1_4_2(cp *entitas.CP, b *bytes.Buffer) string {
	b.WriteString(`
public sealed partial class `)
	b.WriteString(cp.ID().WithoutComponentSuffix().String())
	b.WriteString(`ListenerComponent : Entitas.IComponent 
{
    public System.Collections.Generic.List<I`)
	b.WriteString(cp.ID().WithoutComponentSuffix().String())
	b.WriteString(`Listener> value;
}
`)
	return b.String()

}
