// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\context_matcher\C_1_4_2\context_matcher.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ContextMatcher_C_1_4_2(ctx *model.Context, b *bytes.Buffer) string {
	b.WriteString(`public sealed partial class `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Matcher {

    public static Entitas.IAllOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AllOf(params int[] indices) {
        return Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AllOf(indices);
    }

    public static Entitas.IAllOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AllOf(params Entitas.IMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>[] matchers) {
          return Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AllOf(matchers);
    }

    public static Entitas.IAnyOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AnyOf(params int[] indices) {
          return Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AnyOf(indices);
    }

    public static Entitas.IAnyOfMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity> AnyOf(params Entitas.IMatcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>[] matchers) {
          return Entitas.Matcher<`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity>.AnyOf(matchers);
    }
}
`)
	return b.String()

}
