// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-entitas-generator\csharp\component_entity\C_1_4_2\argument.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func ComponentEntityArgument_C_1_4_2(cp *entitas.CP, b *bytes.Buffer) string {
	ms := cp.MemberList()
	for i, m := range ms {
		b.WriteString(m.Value().String())
		b.WriteRune(' ')
		b.WriteString("new")
		b.WriteString(m.ID().ToUpperFirst().String())
		if i != len(ms)-1 {
			b.WriteString(", ")
		}
	}

	return b.String()

}
