// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\component_entity\C_1_4_2\component_entity_assignment.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ComponentEntityAssignment_C_1_4_2(c *model.Component, b *bytes.Buffer) string {
	ms := c.GetMember()
	for i, m := range ms {
		b.WriteString("\t\tcomponent.")
		b.WriteString(m.GetID().ToLowerFirst().String())
		b.WriteString(" = ")
		b.WriteString("new")
		b.WriteString(m.GetID().ToUpperFirst().String())
		b.WriteRune(';')
		if i != len(ms)-1 {
			b.WriteString("\n")
		}
	}

	return b.String()

}
