// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\go-entitas-generator\csharp\component_entity\C_1_4_2\component_entity.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	entitas "github.com/SirMetathyst/go-entitas"
)

func ComponentEntity_C_1_4_2(c *entitas.C, cp *entitas.CP, b *bytes.Buffer) string {
	b.WriteString(`
public partial class `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity
{
    public `)
	b.WriteString(cp.ID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteRune(' ')
	b.WriteString(cp.ID().WithoutComponentSuffix().ToLowerFirst().String())
	b.WriteString(` 
    { 
        get 
        { 
            return (`)
	b.WriteString(cp.ID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteString(`)GetComponent(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`); 
        } 
    }

    public bool has`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(` 
    { 
        get 
        { 
            return HasComponent(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`); 
        } 
    }

    public void Add`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`(`)
	ComponentEntityArgument_C_1_4_2(cp, b)
	b.WriteString(`) 
    {
        var index = `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`;
        var component = CreateComponent<`)
	b.WriteString(cp.ID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteString(`>(index);
`)
	ComponentEntityAssignment_C_1_4_2(cp, b)
	b.WriteString(`
        AddComponent(index, component);
    }

    public void Replace`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`(`)
	ComponentEntityArgument_C_1_4_2(cp, b)
	b.WriteString(`)
    {
        var index = `)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`;
        var component = CreateComponent<`)
	b.WriteString(cp.ID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteString(`>(index);
`)
	ComponentEntityAssignment_C_1_4_2(cp, b)
	b.WriteString(`
        ReplaceComponent(index, component);
    }

    public void Remove`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`()
    {
        RemoveComponent(`)
	b.WriteString(c.ID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(cp.ID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`);
    }
}
`)
	return b.String()

}
