// Code generated by hero.
// source: C:\Users\alexa\go\src\github.com\SirMetathyst\proton\generator\component_entity\C_1_4_2\component_entity.tpl
// DO NOT EDIT!
package generator

import (
	"bytes"

	"github.com/SirMetathyst/proton/model"
)

func ComponentEntity_C_1_4_2(ctx *model.Context, c *model.Component, b *bytes.Buffer) string {
	b.WriteString(`public partial class `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`Entity {

    public `)
	b.WriteString(c.GetID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteRune(' ')
	b.WriteString(c.GetID().WithoutComponentSuffix().ToLowerFirst().String())
	b.WriteString(` { get { return (`)
	b.WriteString(c.GetID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteString(`)GetComponent(`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`); } }
    public bool `)
	b.WriteString(c.GetPrefixOrDefault().ToLowerFirst().String())
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(` { get { return HasComponent(`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`); } }

    public void Add`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`(`)
	ComponentEntityArgument_C_1_4_2(c, b)
	b.WriteString(`) {
        var index = `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`;
        var component = CreateComponent<`)
	b.WriteString(c.GetID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteString(`>(index);
`)
	ComponentEntityAssignment_C_1_4_2(c, b)
	b.WriteString(`
        AddComponent(index, component);
    }

    public void Replace`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`(`)
	ComponentEntityArgument_C_1_4_2(c, b)
	b.WriteString(`) {
        var index = `)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`;
        var component = CreateComponent<`)
	b.WriteString(c.GetID().WithComponentSuffix().ToUpperFirst().String())
	b.WriteString(`>(index);
`)
	ComponentEntityAssignment_C_1_4_2(c, b)
	b.WriteString(`
        ReplaceComponent(index, component);
    }

    public void Remove`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`() {
        RemoveComponent(`)
	b.WriteString(ctx.GetID().WithoutContextSuffix().ToUpperFirst().String())
	b.WriteString(`ComponentsLookup.`)
	b.WriteString(c.GetID().WithoutComponentSuffix().ToUpperFirst().String())
	b.WriteString(`);
    }
}
`)
	return b.String()

}
